### ISSUE TITLE
0005_RFC for vbucket retries

### ISSUE THREAD

**Issue by ingenthr** [couchbaselabs/sdk-rfcs#10]
@mnunberg and I were talking and there are probably not common implementations in the case of failure.  We should sdk-RFC this when possible.

**Comment by mnunberg** [comment]
For reference, alk's comment on the intended retry logic: https://issues.couchbase.com/browse/MB-12268

The logic is arguably complex, and I believe we only follow some of the rules in here

**Comment by ingenthr** [comment]
Having read the nine-step-plan there, I think we can extract some logic that isn't too bad.  I'd probably end it with step 5 indicated there, to be honest.  What makes me uncomfortable about that thread is that Abhinav indicates that they expect there to be a long latency while they recover checkpoints, so it's entirely reasonable that the app would see the same long latency.  Everything past that sounds like a hack for trying to avoid the behavioral change that was put in place and is, at least from Abhinav's description, expected.

**Comment by daschl** [comment]
Related issue opened by @dave-finlay https://issues.couchbase.com/browse/JCBC-896 - currently in java we have an exponential backoff from 100micros up to 100millis (ceiling), which seems to work completely against the checkpointing semantics. 

Maybe as part of this RFC we can also standardize the retry behavior?

**Comment by dave-finlay** [comment]
+1 for standardizing the behavior. From the server perspective, retry is really important for reasons of safety and if the policies are not very similar across the clients, safety may then depend on which client is being used, which doesn't seem like a good idea. Client and server need to cooperate to provide good behavior across activities like failover, rebalance, random node slowness, etc. Just as it's important for client engineers to know what server behavior is in these transient error situations, it's important for server engineers to know what the standard client behavior is.

**Comment by ingenthr** [comment]
Definitely agree @dave-finlay.  I'd just note that while we can standardize client behavior, we don't really have a method of coordinating application client behavior.  I mention it in this context because we've seen a couple of situations where, when there are thousands of clients, even a "careful" amount of workload is too much.  Thus, at some level or another, the cluster will need to develop ways of protecting itself.

**Comment by dave-finlay** [comment]
@ingenthr 
> Thus, at some level or another, the cluster will need to develop ways of protecting itself.

Totally. I agree both in principle and am open to specific suggestions around NMVB retry in particular.

**Comment by mnunberg** [comment]
There are really several issues/scenarios at hand:

1. Cluster sends us map not reflecting actual vBucket topology changes
2. vBucket may not actually have an owner for a small amount of time. Note that this does _not_ mean a failover scenario (in which case the owner is `-1`, which as far as client semantics are concerned, is straight-forward).
3. Client discovery of owner is overly aggressive

So first we need to figure out what we are solving for, and what we expect the behavior to be as a result: There's a significant difference between "discovering the correct master" (stale map) and "backing off until takeover has actually taken place" (See case 2).

Retry logic should also follow the common use pattern of a given client. For example, Java and C# clients tend to have one large single instance for an entire application, and there are fewer SDK instances per cluster. Contrast this with libcouchbase which typically has one instance per thread, and there are typically many more library instances per cluster.

I'll describe what libcouchbase currently does briefly, which is based off alk's comments in the aforementioned MB issue. The code which does this is here: https://github.com/couchbase/libcouchbase/blob/65966e25ddc13ad553f92591280eceb9e7ba7ef4/src/vbucket/vbucket.c#L888-L935

When an NMV error is encountered, the existing and new (received via CCCP) configurations are inspected to determine if there is a new master for the given vBucket. If no master exists, the 'fast forward vBucket map' is inspected for the same. If no hint of a new master is discovered, the next node (i.e. `(cur_node + 1) % num_nodes`) is used; and is set as the master for all subsequent operations on the vBucket. This happens in a loop.

In the event that there really _is_ a vBucket owner for the given vBucket, this algorithm works well. Indeed in the original MB, the issue filer was satisfied with this algorithm as it properly discovered the vBucket owner with little impact on network and CPU performance.

One enhancement to this algorithm may be to blacklist a vBucket after _n_ iterations have taken place (where _n_ equals the number of servers in the cluster). The blacklist would endure for a fixed interval (let's say 20 seconds), after which the looping algorithm would continue. The blacklist would ensure that each vBucket is only 'scanned' once per interval; if the implicit scan completes without any success the client can deem the vBucket as being temporarily unavailable.

The retry time of course may also be adjusted from _immediate_ to throttled. In libcouchbase we use a linear retry of `14 * n` where _n_ is the number of retry attempts so far. This retry interval is by default set to `0` for not-my-vbucket retries, and that may also be changed (at the expense of slower response times)

**Comment by dhaikney** [comment]
As of releases 3.1.3 and 4.1.0 of Couchbase server, the logic on receiving a NMVB is to include a cluster map in the response. However a combination of (1) reasonably large cluster maps (~65K) and (2) a high number of ops / retries have cause high amounts of network traffic.
Therefore [MB-17506](https://issues.couchbase.com/browse/MB-17506) has been created so that the server will only supply the latest cluster map once per client connection. This will be configurable (off initially but then enabled by default once we are confident all active SDKs are comfortable with this behaviour).

So my first comment about SDK behaviour would be "don't expect NMVB responses to include the cluster map more than once".

Then regarding the retry logic, it would be nice to have consistency across the SDKs for (i) what the default retry behaviour is and (ii) what controls we expose to the users to customise this behaviour. The RFC describes a simple linear retry policy, which is a little simplistic. For clusters with 30k connections and 1M ops / sec, this can be too aggressive. There are a number of parameters which can be used to configure this (I believe Java SDK already exposes many): 
* The initial delay before retry (100ms)
* The exponent with which to backoff  (e.g. 1 for linear, 2 for exponential, 10 for highly exponential). In one customer use case 10 was required to allow quick initial retry without swamping the server. 
* A maximum retry interval  (e.g. don't delay more than 1s between retries)
* An overall timeout on the operation (e.g. 5s)
So for example a default delay of 100ms, an exponent of one, an op timeout of 2s would give 20 retries at 100ms intervals.
A default delay of 5 ms with an exponent of 10, a maximum interval of 1s and an op timeout of 5s would give retries at 5ms, 50ms, 500ms, 1s, 1s, 1s, 1s.

**Comment by mnunberg** [comment]
can you open a PR for this?

**Comment by brett19** [comment]
This has moved to Google Docs:
https://docs.google.com/document/d/1_arBwv6udzIctdaCt6PaW19URm0c0eljsyPPw8I6VkE/edit

**Comment by daschl** [comment]
is accepted and can be closed.
